### ISSUE TITLE
bug: "No module named 'pkg_resources.extern'" when installed with .msi

### ISSUE THREAD

**Issue by Sobsz** [yurijmikhalevich/rclip#134]
Windows 10 21H2, rclip v1.10.2, installed for all users to E: drive.

```
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 200, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 36, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "pkg_resources\__init__.py", line 90, in <module>
ModuleNotFoundError: No module named 'pkg_resources.extern'
[12688] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception!
```

**Comment by yurijmikhalevich** [comment]
@Sobsz, thank you for the report! Will check it out.

**Comment by yurijmikhalevich** [comment]
@Sobsz, I have released [rclip v1.10.3](https://github.com/yurijmikhalevich/rclip/releases/tag/v1.10.3) with the fix for the fix for the Windows build. Can you please confirm that the issue is fixed for you, too?

**Comment by Sobsz** [comment]
Works great, cheers!

**Comment by yurijmikhalevich** [comment]
@Sobsz, perfect 🔥 Thanks for confirming :)
