### ISSUE TITLE
bug(windows): rclip can't search in the drive root on Windows (e.g., in C: or D:)

### ISSUE THREAD

**Issue by yurijmikhalevich** [yurijmikhalevich/rclip#165]
![2024-12-29 19_00_40-C__Windows_System32_cmd exe](https://github.com/user-attachments/assets/2117bf55-81f5-4d37-8224-3423f96153dc)

looks like this :

Microsoft Windows [Version 10.0.19045.3758]
(c) Microsoft Corporation. All rights reserved.

M:\>rclip forest
checking images in the current directory for changes; use "--no-indexing" to skip this if no images were added, changed, or removed
0images [00:00, ?images/s]Exception in thread Thread-2:

Traceback (most recent call last):
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "main.py", line 271, in <module>
  File "threading.py", line 917, in run
  File "main.py", line 244, in main
  File "fs.py", line 15, in count_files
  File "main.py", line 231, in init_rclip
  File "fs.py", line 32, in walk
  File "main.py", line 131, in ensure_index
PermissionError: [WinError 5] Access is denied: 'M:\\System Volume Information'
  File "fs.py", line 32, in walk
PermissionError: [WinError 5] Access is denied: 'M:\\System Volume Information'
[PYI-25368:ERROR] Failed to execute script 'main' due to unhandled exception!

M:\>rclip "forest"
checking images in the current directory for changes; use "--no-indexing" to skip this if no images were added, changed, or removed
0images [00:00, ?images/s]Exception in thread Thread-2:
0images [00:00, ?images/s]Traceback (most recent call last):

  File "threading.py", line 980, in _bootstrap_inner
Traceback (most recent call last):
  File "main.py", line 271, in <module>
  File "threading.py", line 917, in run
  File "main.py", line 244, in main
  File "fs.py", line 15, in count_files
  File "main.py", line 231, in init_rclip
  File "fs.py", line 32, in walk
  File "main.py", line 131, in ensure_index
PermissionError: [WinError 5] Access is denied: 'M:\\System Volume Information'
  File "fs.py", line 32, in walk
PermissionError: [WinError 5] Access is denied: 'M:\\System Volume Information'
[PYI-15304:ERROR] Failed to execute script 'main' due to unhandled exception!

_Originally posted by @FlowDownTheRiver in https://github.com/yurijmikhalevich/rclip/issues/139#issuecomment-2564767436_

**Comment by yurijmikhalevich** [comment]
This needs:
- a test that will run in GHA CI on Windows machines (confirm that it will fail without a fix)
- a fix that makes the test pass

**Comment by Roshansingh9** [comment]
Hi @yurijmikhalevich, I’d like to work on this issue for Hacktoberfest. Could you please assign it to me?

**Comment by yurijmikhalevich** [comment]
@Roshansingh9, thank you for reaching out! Of course. Assigned!

**Comment by yurijmikhalevich** [comment]
@Roshansingh9, I have unassigned you from the issue due to the lack of responses or updates. Let me know if you are working on it.

**Comment by yurijmikhalevich** [comment]
The fix for this issue was released with rclip 2.1.6.
