### ISSUE TITLE
bug(macos/brew): import error on fresh homebrew install

### ISSUE THREAD

**Issue by sweetkane** [yurijmikhalevich/rclip#98]
Homebrew 4.2.12
```
$ brew install yurijmikhalevich/tap/rclip
$ rclip "cat"
---
Traceback (most recent call last):
  File "/opt/homebrew/bin/rclip", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/rclip/1.7.25/libexec/lib/python3.11/site-packages/rclip/main.py", line 205, in main
    arg_parser = helpers.init_arg_parser()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/rclip/1.7.25/libexec/lib/python3.11/site-packages/rclip/utils/helpers.py", line 144, in init_arg_parser
    if is_mps_available():
       ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/rclip/1.7.25/libexec/lib/python3.11/site-packages/rclip/utils/helpers.py", line 153, in is_mps_available
    import torch.backends.mps
ModuleNotFoundError: No module named 'torch'
```

**Comment by sandronm** [comment]
Same here :/ 

(Homebrew 4.2.17, MacOS Sonoma 14.4.1 on M1 Max)

**Comment by yurijmikhalevich** [comment]
@sweetkane, @sandronm, @xvvvyz, @came, @Alkapims, the issue should be fixed after you upgrade rclip installed with brew to the latest version: `brew update && brew upgrade`

Let me know if you still have it.

**Comment by timersys** [comment]
Not for me. I installed rclip and I get:
Traceback (most recent call last):
  File "/opt/homebrew/bin/rclip", line 5, in <module>
    from rclip.main import main
  File "/opt/homebrew/Cellar/rclip/1.10.3/libexec/lib/python3.12/site-packages/rclip/main.py", line 13, in <module>
    from rclip import db, fs, model
  File "/opt/homebrew/Cellar/rclip/1.10.3/libexec/lib/python3.12/site-packages/rclip/model.py", line 10, in <module>
    import open_clip
  File "/opt/homebrew/Cellar/rclip/1.10.3/libexec/lib/python3.12/site-packages/open_clip/__init__.py", line 3, in <module>
    from .coca_model import CoCa
  File "/opt/homebrew/Cellar/rclip/1.10.3/libexec/lib/python3.12/site-packages/open_clip/coca_model.py", line 3, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Then I did brew update && brew upgrade but I still get the same error

**Comment by yurijmikhalevich** [comment]
@timersys, thank you for flagging! I see what's up. Will fix.

**Comment by yurijmikhalevich** [comment]
@timersys, we can lock `rclip`'s Python version in `brew`, but we can't lock `torch`s Python version in `brew` – they made it depend on the latest Python. If there is a disconnect between the two rclip fails.

I am updating rclip Python dep to fix this short term and will think of a long term solution. Maybe, we can have a forked `torch` formula with a fixed version for `rclip` tap.

**Comment by yurijmikhalevich** [comment]
@timersys, a fixed version of rclip was released to `brew`. Can you do `brew update && brew upgrade` and let me know if it fixes this for you?

Sorry about the bad experience, and thank you for flagging this! 🙌 

To prevent this from happening again, I have moved rclip to its own versions of `pytorch` and `torchvision`.

To harden the brewed rclip (and other rclip distributions), I'll do the following:
- https://github.com/yurijmikhalevich/rclip/issues/159
- https://github.com/yurijmikhalevich/rclip/issues/161
- https://github.com/yurijmikhalevich/rclip/issues/160

**Comment by timersys** [comment]
@yurijmikhalevich Excellent job. It sworking and also the pip version.

**Comment by yurijmikhalevich** [comment]
@timersys, thank you for confirming!
